{{- if .Values.clusterScope }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-viewer
rules:
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
    resources:
      - "ingresses"
    verbs:
      - "list"
      - "get"
      - "watch"
{{- end }}