{{- if not .Values.clusterScope }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: entando-plugin
  {{- if .Values.imagePullSecrets }}
imagePullSecrets:
  {{- range $pval := .Values.imagePullSecrets }}
  - name: {{ $pval }}
  {{- end }}
  {{- end }}
{{- end }}
