{{- if not .Values.clusterScope }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-viewer
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - "list"
      - "get"
      - "watch"
{{- end }}