cleanup:
  Args:
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
redhatRegistryCredentials: {{ENTANDO_OPT_IMAGE_REGISTRY_CREDENTIALS}}

preview:
  imagePullSecrets:
    - redhat-registry
  image:
    repository: {{ENTANDO_IMAGE_REPO}}
    tag: {{ENTANDO_IMAGE_TAG}}
    pullPolicy: Always
  env:
    ENTANDO_DOCKER_IMAGE_VERSION_FALLBACK: 6.0.0
    ENTANDO_DOCKER_REGISTRY_FALLBACK: {{ENTANDO_OPT_IMAGE_REGISTRY_OVERRIDE}}
    ENTANDO_DEFAULT_ROUTING_SUFFIX: {{ENTANDO_OPT_TEST_HOSTNAME_SUFFIX}}
    ENTANDO_POD_READINESS_TIMEOUT_SECONDS: "600"
    ENTANDO_POD_COMPLETION_TIMEOUT_SECONDS: "600"
    ENTANDO_DISABLE_KEYCLOAK_SSL_REQUIREMENT: "false"
    ENTANDO_K8S_OPERATOR_SCOPE: namespace
    ENTANDO_K8S_OPERATOR_SECURITY_MODE: strict
    ENTANDO_K8S_OPERATOR_COMPLIANCE_MODE: redhat
    ENTANDO_K8S_OPERATOR_IMAGE_PULL_SECRETS: redhat-registry
    ENTANDO_TLS_SECRET_NAME: test-tls-secret
    ENTANDO_CA_SECRET_NAME: test-ca-secret
  tls:
    tlsSecretName: test-tls-secret
    caCertSecretName: test-ca-cert-secret

# JUST FOR TESTS
testParams:
  tlsSecret:
    crt: {{ENTANDO_OPT_TEST_TLS_CRT}}
    key: {{ENTANDO_OPT_TEST_TLS_KEY}}
