apiVersion: v1
data:
  tls.crt: >-
    {{ .Values.testParams.tlsSecret.crt }}
  tls.key: >-
    {{ .Values.testParams.tlsSecret.key }}
kind: Secret
metadata:
  name: test-tls-secret
type: kubernetes.io/tls
